sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_821a8021f13d_key -iv $encrypted_821a8021f13d_iv -in service-account.pem.enc -out service-account.pem -d
  - AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
  - az aks install-cli
  - az login --service-principal --username "$APP_ID" --tenant "TENANT_ID" --password service-account.pem
  - az aks get-credentials --resource-group k8s-101 --name multi-cluster
  - kubectl get pods
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kviev/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run kviev/react-test npm test -- --coverage
  - docker -v

deploy:
  - docker -v
  # provider: script
  # script: bash ./deploy.sh
  # on:
  #   branch: master
